KEYBALL_ENABLE = yes
VIA_ENABLE = yes
LTO_ENABLE = yes

# OLEDは生かしたまま、他の不要機能を削って容量を確保
OLED_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no

# コンボ機能を有効化
COMBO_ENABLE = yes
