name: Build Keyball44
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile
        run: |
          qmk compile -kb keyball/keyball44 -km via
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: keyball44_firmware
          path: ./*.hex
